
import { Product, Category } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'whey-isolate',
    name_ar: 'DRX - واي بروتين آيزوليت',
    name_en: 'DRX - Whey Protein Isolate',
    description_ar: 'بروتين عالي الجودة وسريع الامتصاص مصمم للاستشفاء العضلي.',
    description_en: 'Fast-absorbing, high-quality protein for muscle recovery.',
    price: 3850,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600&h=600&fit=crop',
    category: Category.Protein,
    rating: 4.8,
    reviews: 124,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    featured: 1,
    goals: ['bulking', 'cutting', 'recovery'],
    sizes: ['500g', '1kg', '2.27kg'],
    flavors: ['Chocolate', 'Vanilla', 'Strawberry'],
  },
  {
    id: 'casein-protein',
    name_ar: 'DRX - كازين بروتين',
    name_en: 'DRX - Casein Protein',
    description_ar: 'بروتين بطيء الامتصاص للاستشفاء المستمر أثناء النوم.',
    description_en: 'Slow-digesting protein for overnight recovery.',
    price: 2100,
    image: 'https://images.unsplash.com/photo-1612532275214-e4ca76d0e4d1?w=600&h=600&fit=crop',
    category: Category.Protein,
    rating: 4.5,
    reviews: 87,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    featured: 2,
    goals: ['bulking', 'recovery'],
    sizes: ['500g', '1kg'],
    flavors: ['Chocolate', 'Vanilla'],
  },
  {
    id: 'whey-concentrate',
    name_ar: 'DRX - واي بروتين مركز 80%',
    name_en: 'DRX - Whey Concentrate 80%',
    description_ar: 'كونسنتريت بروتين متميز لدعم النمو العضلي.',
    description_en: 'Premium concentrate for muscle growth.',
    price: 2950,
    image: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=600&h=600&fit=crop',
    category: Category.Protein,
    rating: 4.3,
    reviews: 56,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    featured: 3,
    goals: ['bulking'],
    sizes: ['1kg', '2.27kg'],
    flavors: ['Chocolate', 'Cookies & Cream'],
  },
  {
    id: 'pre-workout',
    name_ar: 'DRX - تركيبة قبل التمرين',
    name_en: 'DRX - Pre-Workout Formula',
    description_ar: 'تركيبة لتعزيز الطاقة والتركيز والقوة.',
    description_en: 'Boosts energy, focus, and strength.',
    price: 1950,
    image: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=600&h=600&fit=crop',
    category: Category.PreWorkout,
    rating: 4.7,
    reviews: 203,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    featured: 4,
    goals: ['endurance', 'bulking'],
    sizes: ['30 servings', '60 servings'],
    flavors: ['Blue Raspberry', 'Fruit Punch', 'Watermelon'],
  },
  {
    id: 'bcaa-electrolytes',
    name_ar: 'DRX - أحماض أمينية + كهارل',
    name_en: 'DRX - BCAA + Electrolytes',
    description_ar: 'أحماض أمينية وكهارل لمنع الإرهاق العضلي.',
    description_en: 'Amino acids and electrolytes to reduce fatigue.',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=600&h=600&fit=crop',
    category: Category.Recovery,
    rating: 4.4,
    reviews: 78,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    featured: 5,
    goals: ['recovery', 'endurance', 'cutting'],
    sizes: ['30 servings', '60 servings'],
    flavors: ['Lemon Lime', 'Orange', 'Mixed Berry'],
  },
  {
    id: 'creatine-5000',
    name_ar: 'DRX - كرياتين مونوهيدرات 5000',
    name_en: 'DRX - Creatine Monohydrate 5000',
    description_ar: 'كرياتين نقي لزيادة القوة والحجم العضلي.',
    description_en: 'Pure creatine for strength and size.',
    price: 1650,
    image: 'https://images.unsplash.com/photo-1584116831289-e53912463c35?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.9,
    reviews: 312,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    featured: 6,
    goals: ['bulking', 'endurance'],
    sizes: ['250g', '500g'],
    flavors: ['Unflavored'],
  },
  {
    id: 'beta-alanine',
    name_ar: 'DRX - بيتا ألانين',
    name_en: 'DRX - Beta-Alanine',
    description_ar: 'يؤخر التعب العضلي ويزيد من قوة التحمل.',
    description_en: 'Delays fatigue and improves endurance.',
    price: 950,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.2,
    reviews: 45,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    featured: 7,
    goals: ['endurance'],
    sizes: ['200g', '400g'],
    flavors: ['Unflavored'],
  },
  {
    id: 'l-citrulline',
    name_ar: 'DRX - إل-سيترولين',
    name_en: 'DRX - L-Citrulline',
    description_ar: 'يعزز تدفق الدم والمضخة العضلية.',
    description_en: 'Supports blood flow and muscle pump.',
    price: 1400,
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.1,
    reviews: 34,
    inStock: false,
    isNew: false,
    isBestSeller: false,
    featured: 8,
    goals: ['endurance', 'bulking'],
    sizes: ['200g'],
    flavors: ['Unflavored'],
  },
  {
    id: 'electrolyte-complex',
    name_ar: 'DRX - خليط الكهارل',
    name_en: 'DRX - Electrolyte Complex',
    description_ar: 'تركيبة ترطيب متكاملة لمنع الجفاف.',
    description_en: 'Complete hydration blend.',
    price: 850,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop',
    category: Category.Wellness,
    rating: 4.6,
    reviews: 91,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    featured: 9,
    goals: ['endurance', 'recovery'],
    sizes: ['30 servings'],
    flavors: ['Citrus', 'Berry'],
  },
  {
    id: 'l-glutamine',
    name_ar: 'DRX - إل-جلوتامين 5000',
    name_en: 'DRX - L-Glutamine 5000',
    description_ar: 'دعم الاستشفاء العضلي ومنع الهدم.',
    description_en: 'Supports recovery and reduces breakdown.',
    price: 1100,
    image: 'https://images.unsplash.com/photo-1619785292559-a15caa28bde6?w=600&h=600&fit=crop',
    category: Category.Recovery,
    rating: 4.5,
    reviews: 67,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    featured: 10,
    goals: ['recovery'],
    sizes: ['250g', '500g'],
    flavors: ['Unflavored'],
  },
  {
    id: 'l-arginine',
    name_ar: 'DRX - إل-أرجينين HCl 5000',
    name_en: 'DRX - L-Arginine HCl 5000',
    description_ar: 'يعزز الأوعية الدموية وإنتاج أكسيد النيتريك.',
    description_en: 'Boosts nitric oxide for vascularity.',
    price: 1350,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.3,
    reviews: 42,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    featured: 11,
    goals: ['bulking', 'endurance'],
    sizes: ['250g'],
    flavors: ['Unflavored'],
  },
  {
    id: 'l-tyrosine',
    name_ar: 'DRX - إل-تيروزين',
    name_en: 'DRX - L-Tyrosine',
    description_ar: 'يدعم التركيز الذهني أثناء التدريب المكثف.',
    description_en: 'Enhances mental focus during training.',
    price: 1800,
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.0,
    reviews: 29,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    featured: 12,
    goals: ['endurance'],
    sizes: ['60 capsules', '120 capsules'],
  },
  {
    id: 'taurine',
    name_ar: 'DRX - تورين',
    name_en: 'DRX - Taurine',
    description_ar: 'يدعم وظائف العضلات والتمثيل الغذائي للطاقة.',
    description_en: 'Supports muscle function and energy.',
    price: 1150,
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.1,
    reviews: 38,
    inStock: false,
    isNew: false,
    isBestSeller: false,
    featured: 13,
    goals: ['endurance', 'recovery'],
    sizes: ['250g'],
    flavors: ['Unflavored'],
  },
  {
    id: 'betaine',
    name_ar: 'DRX - بيتاين 2500',
    name_en: 'DRX - Betaine 2500',
    description_ar: 'يزيد القوة ويعزز القدرة على التحمل.',
    description_en: 'Improves strength and endurance.',
    price: 2250,
    image: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.4,
    reviews: 53,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    featured: 14,
    goals: ['bulking', 'endurance'],
    sizes: ['200g'],
    flavors: ['Unflavored'],
  },
  {
    id: 'l-alanine',
    name_ar: 'DRX - إل-ألانين 6000',
    name_en: 'DRX - L-Alanine 6000',
    description_ar: 'يدعم إنتاج الطاقة أثناء التمارين عالية الكثافة.',
    description_en: 'Supports energy for high-intensity workouts.',
    price: 950,
    image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.0,
    reviews: 22,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    featured: 15,
    goals: ['endurance'],
    sizes: ['300g'],
    flavors: ['Unflavored'],
  },
  {
    id: 'carbohydrate',
    name_ar: 'DRX - مركب الكربوهيدرات',
    name_en: 'DRX - Carbohydrate Complex',
    description_ar: 'وقود سريع الهضم لتعويض الجليكوجين.',
    description_en: 'Fast fuel to restore glycogen.',
    price: 750,
    image: 'https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.2,
    reviews: 31,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    featured: 16,
    goals: ['bulking', 'endurance'],
    sizes: ['1kg', '2kg'],
    flavors: ['Unflavored', 'Orange'],
  },
  {
    id: 'caffeine',
    name_ar: 'DRX - كافيين 200',
    name_en: 'DRX - Caffeine 200',
    description_ar: 'محفز نقي للطاقة والتركيز.',
    description_en: 'Pure stimulant for energy and focus.',
    price: 1250,
    image: 'https://images.unsplash.com/photo-1495521939206-a217db9df264?w=600&h=600&fit=crop',
    category: Category.Performance,
    rating: 4.6,
    reviews: 156,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    featured: 17,
    goals: ['cutting', 'endurance'],
    sizes: ['60 capsules', '120 capsules'],
  }
];

export const CATEGORIES = [
  'All Products',
  'Protein',
  'Performance',
  'Pre-Workout',
  'Recovery',
  'Health & Wellness',
];

export const GOALS = [
  { id: 'bulking', label_ar: 'ضخامة عضلية', label_en: 'Bulking', emoji: '💪' },
  { id: 'cutting', label_ar: 'تنشيف', label_en: 'Cutting', emoji: '🔥' },
  { id: 'endurance', label_ar: 'تحمل', label_en: 'Endurance', emoji: '⚡' },
  { id: 'recovery', label_ar: 'استشفاء', label_en: 'Recovery', emoji: '🧘' }
];

export const ACTIVITY_LEVELS = [
  { id: 'sedentary', label_ar: 'خامل (مكتب)', label_en: 'Sedentary' },
  { id: 'light', label_ar: 'نشاط خفيف (1-3 أيام)', label_en: 'Lightly Active' },
  { id: 'moderate', label_ar: 'نشاط متوسط (3-5 أيام)', label_en: 'Moderately Active' },
  { id: 'heavy', label_ar: 'نشاط عالي (6-7 أيام)', label_en: 'Very Active' },
  { id: 'extreme', label_ar: 'نشاط رياضي محترف', label_en: 'Extreme Athlete' }
];
