-- Security improvements for DRX EGYPT

-- 1. Secure Guest Order Tracking
-- Add hash column to orders table for secure guest lookup
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'guest_tracking_token_hash') THEN
        ALTER TABLE "public"."orders" ADD COLUMN "guest_tracking_token_hash" text;
    END IF;
END $$;

-- Create table specifically for tracking guest lookup attempts (rate limiting)
CREATE TABLE IF NOT EXISTS "public"."guest_order_lookup_attempts" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ip" text NOT NULL,
    "token_fingerprint" text,
    "attempted_at" timestamp with time zone DEFAULT now() NOT NULL
);

-- Enable RLS on the new table
ALTER TABLE "public"."guest_order_lookup_attempts" ENABLE ROW LEVEL SECURITY;

-- Allow insert by service role (edge function)
-- Note: Edge functions usually use service_role key which bypasses RLS unless specifically configured not to.
-- Standard policy might not be needed if accessed via service_role, but good practice to define stricter rules if accessed by anon.
-- Anonymous users shouldn't create attempts directly via API, only via Edge Function.
-- So no public policy needed for INSERT if strictly using Edge Function.

-- 2. Secure Profiles Access
-- Ensure RLS is enabled
ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

-- Add policy for admins to view all profiles
-- First drop to avoid conflict
DROP POLICY IF EXISTS "Admins can view all profiles" ON "public"."profiles";

CREATE POLICY "Admins can view all profiles" ON "public"."profiles"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (
  ((auth.jwt() ->> 'role'::text) = 'service_role'::text)
  OR 
  (auth.uid() IN ( SELECT id FROM profiles WHERE is_admin = true ))
);

-- 3. Secure Order Items
-- Restrict access to order items to the owner of the order
DROP POLICY IF EXISTS "Public can view order items" ON "public"."order_items";
DROP POLICY IF EXISTS "Users can view own order items" ON "public"."order_items";

CREATE POLICY "Users can view own order items" ON "public"."order_items"
AS PERMISSIVE FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM orders
    WHERE orders.id = order_items.order_id
    AND orders.user_id = auth.uid()
  )
);

-- Note: Guest access to order items is handled via `track-order` Edge Function (service role), 
-- so no public access policy is needed for "order_items" table directly.
